### ISSUE TITLE
게임을 시작하는 버튼

### ISSUE THREAD

**Issue by G0325g** [OpenSource-9/OpenSource-9#10]
사이트에 들어가자마자 게임이 실행되는데,
사이트에 들어가면 일단 게임을 실행하지 않다가 (게임 타이틀 화면 등 출력으로 멈춰둠)
PLAY 버튼을 눌렀을 때 게임이 실행되게 하면 어떨까요?

**Comment by fghy788** [comment]
https://github.com/OpenSource-9/OpenSource-9/pull/13

체크부탁드립니다!
