### ISSUE TITLE
게임오버 후, Score창에 갔다오면 점수 초기화 안됨

### ISSUE THREAD

**Issue by G0325g** [OpenSource-9/OpenSource-9#12]
게임오버 후, SCORE창에 이동하였다가 다시 GAME으로 돌아오면
이전 판의 score가 초기화 되지 않고 그대로 유지됩니다. 

![스크린샷 2024-06-11 163706](https://github.com/OpenSource-9/OpenSource-9/assets/119734946/9777f616-d387-4ceb-9d92-3bfb900eae13)

![스크린샷 2024-06-11 163719](https://github.com/OpenSource-9/OpenSource-9/assets/119734946/1332df94-2fca-4bfb-99a7-2844a16cd40a)

**Comment by fghy788** [comment]
감사합니다! 확인해서 수정했습니다.중요한 버그픽스 같아서 master브랜치로 바로 커밋됐습니다.
