### ISSUE TITLE
게임 컨셉 회의

### ISSUE THREAD

**Issue by fghy788** [OpenSource-9/OpenSource-9#2]
간단한 3D 미니게임의 컨셉을 제안해주세요

**Comment by G0325g** [comment]
장애물, 지형지물 등을 피하며 최대한 오래 생존하는 러닝게임을 제안합니다.

**Comment by fghy788** [comment]
좋은것 같은데 컨셉은 뭘로할까요? 바다, 용암피하기 등등중에서 좋은게있을까요?!

**Comment by G0325g** [comment]
전 용암이 위험한 느낌이 들어서, 용암 피하기가 괜찮을 것 같습니다!

**Comment by fghy788** [comment]
용암피하기로 진행하시죠!!
