### ISSUE TITLE
스코어 보드 서버 연동

### ISSUE THREAD

**Issue by fghy788** [OpenSource-9/OpenSource-9#3]
서버 연동이 필요합니다.

**Comment by Koopang** [comment]
서버 레포에 올렸구, api는 Rest Api를 이용하였습니다.
사용방법은  저장 : POST url/users/save       body는  json형식으로 {name: string, score: number}형식이며,
랭크: GET url/users/rank 
입니다.

**Comment by fghy788** [comment]
localhost:3000에서 실행하면 CORS오류 뜨는데 해결이 필요합니다.

**Comment by Koopang** [comment]
오류 부분 인지하였고, CORS오류 수정하였습니다.

**Comment by fghy788** [comment]
넵 잘되네요! 감사합니다!
