### ISSUE TITLE
GAME OVER 창이 사라지지 않는 오류

### ISSUE THREAD

**Issue by G0325g** [OpenSource-9/OpenSource-9#5]
게임 종료 시, 재시작 하거나 SCORE 창으로 이동해도 GAME OVER 창이 사라지지 않는 오류가 있습니다. 

![스크린샷 2024-06-09 202749](https://github.com/OpenSource-9/OpenSource-9/assets/119734946/0da96f2c-0f44-44c8-9dc8-f8397c3f9ebd)

**Comment by fghy788** [comment]
버그 제보 감사합니다~! 제가 해결해서 업데이트 해두었습니다!
